"""Generated message classes for dataflow version v1beta3.

Google Dataflow API.
"""
# NOTE: This file is autogenerated and should not be edited by hand.

from protorpc import messages

from googlecloudapis.apitools.base.py import encoding
from googlecloudapis.apitools.base.py import extra_types


package = 'dataflow'


class ApproximateProgress(messages.Message):
  """A ApproximateProgress object.

  Fields:
    percentComplete: A number attribute.
    position: A Position attribute.
    remainingTime: A string attribute.
  """

  percentComplete = messages.FloatField(1, variant=messages.Variant.FLOAT)
  position = messages.MessageField('Position', 2)
  remainingTime = messages.StringField(3)


class AutoscalingSettings(messages.Message):
  """A AutoscalingSettings object.

  Enums:
    AlgorithmValueValuesEnum:

  Fields:
    algorithm: A AlgorithmValueValuesEnum attribute.
    maxNumWorkers: A integer attribute.
  """

  class AlgorithmValueValuesEnum(messages.Enum):
    """AlgorithmValueValuesEnum enum type.

    Values:
      AUTOSCALING_ALGORITHM_BASIC: <no description>
      AUTOSCALING_ALGORITHM_NONE: <no description>
      AUTOSCALING_ALGORITHM_UNKNOWN: <no description>
    """
    AUTOSCALING_ALGORITHM_BASIC = 0
    AUTOSCALING_ALGORITHM_NONE = 1
    AUTOSCALING_ALGORITHM_UNKNOWN = 2

  algorithm = messages.EnumField('AlgorithmValueValuesEnum', 1)
  maxNumWorkers = messages.IntegerField(2, variant=messages.Variant.INT32)


class ComputationTopology(messages.Message):
  """A ComputationTopology object.

  Fields:
    computationId: A string attribute.
    inputs: A StreamLocation attribute.
    keyRanges: A KeyRangeLocation attribute.
    outputs: A StreamLocation attribute.
  """

  computationId = messages.StringField(1)
  inputs = messages.MessageField('StreamLocation', 2, repeated=True)
  keyRanges = messages.MessageField('KeyRangeLocation', 3, repeated=True)
  outputs = messages.MessageField('StreamLocation', 4, repeated=True)


class DataDiskAssignment(messages.Message):
  """A DataDiskAssignment object.

  Fields:
    dataDisks: A string attribute.
    vmInstance: A string attribute.
  """

  dataDisks = messages.StringField(1, repeated=True)
  vmInstance = messages.StringField(2)


class DataflowV1b3ProjectsJobsCreateRequest(messages.Message):
  """A DataflowV1b3ProjectsJobsCreateRequest object.

  Enums:
    ViewValueValuesEnum:

  Fields:
    job: A Job resource to be passed as the request body.
    projectId: A string attribute.
    view: A ViewValueValuesEnum attribute.
  """

  class ViewValueValuesEnum(messages.Enum):
    """ViewValueValuesEnum enum type.

    Values:
      JOB_VIEW_ALL: <no description>
      JOB_VIEW_SUMMARY: <no description>
      JOB_VIEW_UNKNOWN: <no description>
    """
    JOB_VIEW_ALL = 0
    JOB_VIEW_SUMMARY = 1
    JOB_VIEW_UNKNOWN = 2

  job = messages.MessageField('Job', 1)
  projectId = messages.StringField(2, required=True)
  view = messages.EnumField('ViewValueValuesEnum', 3)


class DataflowV1b3ProjectsJobsGetMetricsRequest(messages.Message):
  """A DataflowV1b3ProjectsJobsGetMetricsRequest object.

  Fields:
    jobId: A string attribute.
    projectId: A string attribute.
    startTime: A string attribute.
  """

  jobId = messages.StringField(1, required=True)
  projectId = messages.StringField(2, required=True)
  startTime = messages.StringField(3)


class DataflowV1b3ProjectsJobsGetRequest(messages.Message):
  """A DataflowV1b3ProjectsJobsGetRequest object.

  Enums:
    ViewValueValuesEnum:

  Fields:
    jobId: A string attribute.
    projectId: A string attribute.
    view: A ViewValueValuesEnum attribute.
  """

  class ViewValueValuesEnum(messages.Enum):
    """ViewValueValuesEnum enum type.

    Values:
      JOB_VIEW_ALL: <no description>
      JOB_VIEW_SUMMARY: <no description>
      JOB_VIEW_UNKNOWN: <no description>
    """
    JOB_VIEW_ALL = 0
    JOB_VIEW_SUMMARY = 1
    JOB_VIEW_UNKNOWN = 2

  jobId = messages.StringField(1, required=True)
  projectId = messages.StringField(2, required=True)
  view = messages.EnumField('ViewValueValuesEnum', 3)


class DataflowV1b3ProjectsJobsListRequest(messages.Message):
  """A DataflowV1b3ProjectsJobsListRequest object.

  Enums:
    ViewValueValuesEnum:

  Fields:
    pageSize: A integer attribute.
    pageToken: A string attribute.
    projectId: A string attribute.
    view: A ViewValueValuesEnum attribute.
  """

  class ViewValueValuesEnum(messages.Enum):
    """ViewValueValuesEnum enum type.

    Values:
      JOB_VIEW_ALL: <no description>
      JOB_VIEW_SUMMARY: <no description>
      JOB_VIEW_UNKNOWN: <no description>
    """
    JOB_VIEW_ALL = 0
    JOB_VIEW_SUMMARY = 1
    JOB_VIEW_UNKNOWN = 2

  pageSize = messages.IntegerField(1, variant=messages.Variant.INT32)
  pageToken = messages.StringField(2)
  projectId = messages.StringField(3, required=True)
  view = messages.EnumField('ViewValueValuesEnum', 4)


class DataflowV1b3ProjectsJobsMessagesListRequest(messages.Message):
  """A DataflowV1b3ProjectsJobsMessagesListRequest object.

  Enums:
    MinimumImportanceValueValuesEnum:

  Fields:
    endTime: A string attribute.
    jobId: A string attribute.
    minimumImportance: A MinimumImportanceValueValuesEnum attribute.
    pageSize: A integer attribute.
    pageToken: A string attribute.
    projectId: A string attribute.
    startTime: A string attribute.
  """

  class MinimumImportanceValueValuesEnum(messages.Enum):
    """MinimumImportanceValueValuesEnum enum type.

    Values:
      JOB_MESSAGE_DEBUG: <no description>
      JOB_MESSAGE_DETAILED: <no description>
      JOB_MESSAGE_ERROR: <no description>
      JOB_MESSAGE_IMPORTANCE_UNKNOWN: <no description>
      JOB_MESSAGE_WARNING: <no description>
    """
    JOB_MESSAGE_DEBUG = 0
    JOB_MESSAGE_DETAILED = 1
    JOB_MESSAGE_ERROR = 2
    JOB_MESSAGE_IMPORTANCE_UNKNOWN = 3
    JOB_MESSAGE_WARNING = 4

  endTime = messages.StringField(1)
  jobId = messages.StringField(2, required=True)
  minimumImportance = messages.EnumField('MinimumImportanceValueValuesEnum', 3)
  pageSize = messages.IntegerField(4, variant=messages.Variant.INT32)
  pageToken = messages.StringField(5)
  projectId = messages.StringField(6, required=True)
  startTime = messages.StringField(7)


class DataflowV1b3ProjectsJobsPatchRequest(messages.Message):
  """A DataflowV1b3ProjectsJobsPatchRequest object.

  Fields:
    job: A Job resource to be passed as the request body.
    jobId: A string attribute.
    projectId: A string attribute.
  """

  job = messages.MessageField('Job', 1)
  jobId = messages.StringField(2, required=True)
  projectId = messages.StringField(3, required=True)


class DataflowV1b3ProjectsJobsUpdateRequest(messages.Message):
  """A DataflowV1b3ProjectsJobsUpdateRequest object.

  Fields:
    job: A Job resource to be passed as the request body.
    jobId: A string attribute.
    projectId: A string attribute.
  """

  job = messages.MessageField('Job', 1)
  jobId = messages.StringField(2, required=True)
  projectId = messages.StringField(3, required=True)


class DataflowV1b3ProjectsJobsWorkItemsLeaseRequest(messages.Message):
  """A DataflowV1b3ProjectsJobsWorkItemsLeaseRequest object.

  Fields:
    jobId: A string attribute.
    leaseWorkItemRequest: A LeaseWorkItemRequest resource to be passed as the
      request body.
    projectId: A string attribute.
  """

  jobId = messages.StringField(1, required=True)
  leaseWorkItemRequest = messages.MessageField('LeaseWorkItemRequest', 2)
  projectId = messages.StringField(3, required=True)


class DataflowV1b3ProjectsJobsWorkItemsReportStatusRequest(messages.Message):
  """A DataflowV1b3ProjectsJobsWorkItemsReportStatusRequest object.

  Fields:
    jobId: A string attribute.
    projectId: A string attribute.
    reportWorkItemStatusRequest: A ReportWorkItemStatusRequest resource to be
      passed as the request body.
  """

  jobId = messages.StringField(1, required=True)
  projectId = messages.StringField(2, required=True)
  reportWorkItemStatusRequest = messages.MessageField('ReportWorkItemStatusRequest', 3)


class Disk(messages.Message):
  """A Disk object.

  Fields:
    diskType: A string attribute.
    mountPoint: A string attribute.
    sizeGb: A integer attribute.
  """

  diskType = messages.StringField(1)
  mountPoint = messages.StringField(2)
  sizeGb = messages.IntegerField(3, variant=messages.Variant.INT32)


class Environment(messages.Message):
  """A Environment object.

  Messages:
    SdkPipelineOptionsValue: A SdkPipelineOptionsValue object.
    UserAgentValue: A UserAgentValue object.
    VersionValue: A VersionValue object.

  Fields:
    clusterManagerApiService: A string attribute.
    dataset: A string attribute.
    experiments: A string attribute.
    sdkPipelineOptions: A SdkPipelineOptionsValue attribute.
    tempStoragePrefix: A string attribute.
    userAgent: A UserAgentValue attribute.
    version: A VersionValue attribute.
    workerPools: A WorkerPool attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class SdkPipelineOptionsValue(messages.Message):
    """A SdkPipelineOptionsValue object.

    Messages:
      AdditionalProperty: An additional property for a SdkPipelineOptionsValue
        object.

    Fields:
      additionalProperties: Additional properties of type
        SdkPipelineOptionsValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a SdkPipelineOptionsValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class UserAgentValue(messages.Message):
    """A UserAgentValue object.

    Messages:
      AdditionalProperty: An additional property for a UserAgentValue object.

    Fields:
      additionalProperties: Additional properties of type UserAgentValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a UserAgentValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class VersionValue(messages.Message):
    """A VersionValue object.

    Messages:
      AdditionalProperty: An additional property for a VersionValue object.

    Fields:
      additionalProperties: Additional properties of type VersionValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a VersionValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  clusterManagerApiService = messages.StringField(1)
  dataset = messages.StringField(2)
  experiments = messages.StringField(3, repeated=True)
  sdkPipelineOptions = messages.MessageField('SdkPipelineOptionsValue', 4)
  tempStoragePrefix = messages.StringField(5)
  userAgent = messages.MessageField('UserAgentValue', 6)
  version = messages.MessageField('VersionValue', 7)
  workerPools = messages.MessageField('WorkerPool', 8, repeated=True)


class FlattenInstruction(messages.Message):
  """A FlattenInstruction object.

  Fields:
    inputs: A InstructionInput attribute.
  """

  inputs = messages.MessageField('InstructionInput', 1, repeated=True)


GoogleprotobufValue = extra_types.JsonValue


class InstructionInput(messages.Message):
  """A InstructionInput object.

  Fields:
    outputNum: A integer attribute.
    producerInstructionIndex: A integer attribute.
  """

  outputNum = messages.IntegerField(1, variant=messages.Variant.INT32)
  producerInstructionIndex = messages.IntegerField(2, variant=messages.Variant.INT32)


class InstructionOutput(messages.Message):
  """A InstructionOutput object.

  Messages:
    CodecValue: A CodecValue object.

  Fields:
    codec: A CodecValue attribute.
    name: A string attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class CodecValue(messages.Message):
    """A CodecValue object.

    Messages:
      AdditionalProperty: An additional property for a CodecValue object.

    Fields:
      additionalProperties: Additional properties of type CodecValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a CodecValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  codec = messages.MessageField('CodecValue', 1)
  name = messages.StringField(2)


class Job(messages.Message):
  """A Job object.

  Enums:
    CurrentStateValueValuesEnum:
    RequestedStateValueValuesEnum:
    TypeValueValuesEnum:

  Fields:
    createTime: A string attribute.
    currentState: A CurrentStateValueValuesEnum attribute.
    currentStateTime: A string attribute.
    environment: A Environment attribute.
    executionInfo: A JobExecutionInfo attribute.
    id: A string attribute.
    name: A string attribute.
    projectId: A string attribute.
    requestedState: A RequestedStateValueValuesEnum attribute.
    steps: A Step attribute.
    type: A TypeValueValuesEnum attribute.
  """

  class CurrentStateValueValuesEnum(messages.Enum):
    """CurrentStateValueValuesEnum enum type.

    Values:
      JOB_STATE_CANCELLED: <no description>
      JOB_STATE_DONE: <no description>
      JOB_STATE_FAILED: <no description>
      JOB_STATE_RUNNING: <no description>
      JOB_STATE_STOPPED: <no description>
      JOB_STATE_UNKNOWN: <no description>
    """
    JOB_STATE_CANCELLED = 0
    JOB_STATE_DONE = 1
    JOB_STATE_FAILED = 2
    JOB_STATE_RUNNING = 3
    JOB_STATE_STOPPED = 4
    JOB_STATE_UNKNOWN = 5

  class RequestedStateValueValuesEnum(messages.Enum):
    """RequestedStateValueValuesEnum enum type.

    Values:
      JOB_STATE_CANCELLED: <no description>
      JOB_STATE_DONE: <no description>
      JOB_STATE_FAILED: <no description>
      JOB_STATE_RUNNING: <no description>
      JOB_STATE_STOPPED: <no description>
      JOB_STATE_UNKNOWN: <no description>
    """
    JOB_STATE_CANCELLED = 0
    JOB_STATE_DONE = 1
    JOB_STATE_FAILED = 2
    JOB_STATE_RUNNING = 3
    JOB_STATE_STOPPED = 4
    JOB_STATE_UNKNOWN = 5

  class TypeValueValuesEnum(messages.Enum):
    """TypeValueValuesEnum enum type.

    Values:
      JOB_TYPE_BATCH: <no description>
      JOB_TYPE_STREAMING: <no description>
      JOB_TYPE_UNKNOWN: <no description>
    """
    JOB_TYPE_BATCH = 0
    JOB_TYPE_STREAMING = 1
    JOB_TYPE_UNKNOWN = 2

  createTime = messages.StringField(1)
  currentState = messages.EnumField('CurrentStateValueValuesEnum', 2)
  currentStateTime = messages.StringField(3)
  environment = messages.MessageField('Environment', 4)
  executionInfo = messages.MessageField('JobExecutionInfo', 5)
  id = messages.StringField(6)
  name = messages.StringField(7)
  projectId = messages.StringField(8)
  requestedState = messages.EnumField('RequestedStateValueValuesEnum', 9)
  steps = messages.MessageField('Step', 10, repeated=True)
  type = messages.EnumField('TypeValueValuesEnum', 11)


class JobExecutionInfo(messages.Message):
  """A JobExecutionInfo object.

  Messages:
    StagesValue: A StagesValue object.

  Fields:
    stages: A StagesValue attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class StagesValue(messages.Message):
    """A StagesValue object.

    Messages:
      AdditionalProperty: An additional property for a StagesValue object.

    Fields:
      additionalProperties: Additional properties of type StagesValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a StagesValue object.

      Fields:
        key: Name of the additional property.
        value: A JobExecutionStageInfo attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('JobExecutionStageInfo', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  stages = messages.MessageField('StagesValue', 1)


class JobExecutionStageInfo(messages.Message):
  """A JobExecutionStageInfo object.

  Fields:
    stepName: A string attribute.
  """

  stepName = messages.StringField(1, repeated=True)


class JobMessage(messages.Message):
  """A JobMessage object.

  Enums:
    MessageImportanceValueValuesEnum:

  Fields:
    id: A string attribute.
    messageImportance: A MessageImportanceValueValuesEnum attribute.
    messageText: A string attribute.
    time: A string attribute.
  """

  class MessageImportanceValueValuesEnum(messages.Enum):
    """MessageImportanceValueValuesEnum enum type.

    Values:
      JOB_MESSAGE_DEBUG: <no description>
      JOB_MESSAGE_DETAILED: <no description>
      JOB_MESSAGE_ERROR: <no description>
      JOB_MESSAGE_IMPORTANCE_UNKNOWN: <no description>
      JOB_MESSAGE_WARNING: <no description>
    """
    JOB_MESSAGE_DEBUG = 0
    JOB_MESSAGE_DETAILED = 1
    JOB_MESSAGE_ERROR = 2
    JOB_MESSAGE_IMPORTANCE_UNKNOWN = 3
    JOB_MESSAGE_WARNING = 4

  id = messages.StringField(1)
  messageImportance = messages.EnumField('MessageImportanceValueValuesEnum', 2)
  messageText = messages.StringField(3)
  time = messages.StringField(4)


class JobMetrics(messages.Message):
  """A JobMetrics object.

  Fields:
    metricTime: A string attribute.
    metrics: A MetricUpdate attribute.
  """

  metricTime = messages.StringField(1)
  metrics = messages.MessageField('MetricUpdate', 2, repeated=True)


class KeyRangeDataDiskAssignment(messages.Message):
  """A KeyRangeDataDiskAssignment object.

  Fields:
    dataDisk: A string attribute.
    end: A string attribute.
    start: A string attribute.
  """

  dataDisk = messages.StringField(1)
  end = messages.StringField(2)
  start = messages.StringField(3)


class KeyRangeLocation(messages.Message):
  """A KeyRangeLocation object.

  Fields:
    dataDisk: A string attribute.
    deliveryEndpoint: A string attribute.
    end: A string attribute.
    persistentDirectory: A string attribute.
    start: A string attribute.
  """

  dataDisk = messages.StringField(1)
  deliveryEndpoint = messages.StringField(2)
  end = messages.StringField(3)
  persistentDirectory = messages.StringField(4)
  start = messages.StringField(5)


class LeaseWorkItemRequest(messages.Message):
  """A LeaseWorkItemRequest object.

  Fields:
    currentWorkerTime: A string attribute.
    requestedLeaseDuration: A string attribute.
    workItemTypes: A string attribute.
    workerCapabilities: A string attribute.
    workerId: A string attribute.
  """

  currentWorkerTime = messages.StringField(1)
  requestedLeaseDuration = messages.StringField(2)
  workItemTypes = messages.StringField(3, repeated=True)
  workerCapabilities = messages.StringField(4, repeated=True)
  workerId = messages.StringField(5)


class LeaseWorkItemResponse(messages.Message):
  """A LeaseWorkItemResponse object.

  Fields:
    workItems: A WorkItem attribute.
  """

  workItems = messages.MessageField('WorkItem', 1, repeated=True)


class ListJobMessagesResponse(messages.Message):
  """A ListJobMessagesResponse object.

  Fields:
    jobMessages: A JobMessage attribute.
    nextPageToken: A string attribute.
  """

  jobMessages = messages.MessageField('JobMessage', 1, repeated=True)
  nextPageToken = messages.StringField(2)


class ListJobsResponse(messages.Message):
  """A ListJobsResponse object.

  Fields:
    jobs: A Job attribute.
    nextPageToken: A string attribute.
  """

  jobs = messages.MessageField('Job', 1, repeated=True)
  nextPageToken = messages.StringField(2)


class MapTask(messages.Message):
  """A MapTask object.

  Fields:
    instructions: A ParallelInstruction attribute.
    stageName: A string attribute.
    systemName: A string attribute.
  """

  instructions = messages.MessageField('ParallelInstruction', 1, repeated=True)
  stageName = messages.StringField(2)
  systemName = messages.StringField(3)


class MetricStructuredName(messages.Message):
  """A MetricStructuredName object.

  Messages:
    ContextValue: A ContextValue object.

  Fields:
    context: A ContextValue attribute.
    name: A string attribute.
    origin: A string attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class ContextValue(messages.Message):
    """A ContextValue object.

    Messages:
      AdditionalProperty: An additional property for a ContextValue object.

    Fields:
      additionalProperties: Additional properties of type ContextValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a ContextValue object.

      Fields:
        key: Name of the additional property.
        value: A string attribute.
      """

      key = messages.StringField(1)
      value = messages.StringField(2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  context = messages.MessageField('ContextValue', 1)
  name = messages.StringField(2)
  origin = messages.StringField(3)


class MetricUpdate(messages.Message):
  """A MetricUpdate object.

  Fields:
    cumulative: A boolean attribute.
    internal: A GoogleprotobufValue attribute.
    kind: A string attribute.
    meanCount: A GoogleprotobufValue attribute.
    meanSum: A GoogleprotobufValue attribute.
    name: A MetricStructuredName attribute.
    scalar: A GoogleprotobufValue attribute.
    set: A GoogleprotobufValue attribute.
    updateTime: A string attribute.
  """

  cumulative = messages.BooleanField(1)
  internal = messages.MessageField('GoogleprotobufValue', 2)
  kind = messages.StringField(3)
  meanCount = messages.MessageField('GoogleprotobufValue', 4)
  meanSum = messages.MessageField('GoogleprotobufValue', 5)
  name = messages.MessageField('MetricStructuredName', 6)
  scalar = messages.MessageField('GoogleprotobufValue', 7)
  set = messages.MessageField('GoogleprotobufValue', 8)
  updateTime = messages.StringField(9)


class MountedDataDisk(messages.Message):
  """A MountedDataDisk object.

  Fields:
    dataDisk: A string attribute.
  """

  dataDisk = messages.StringField(1)


class MultiOutputInfo(messages.Message):
  """A MultiOutputInfo object.

  Fields:
    tag: A string attribute.
  """

  tag = messages.StringField(1)


class Package(messages.Message):
  """A Package object.

  Fields:
    location: A string attribute.
    name: A string attribute.
  """

  location = messages.StringField(1)
  name = messages.StringField(2)


class ParDoInstruction(messages.Message):
  """A ParDoInstruction object.

  Messages:
    UserFnValue: A UserFnValue object.

  Fields:
    input: A InstructionInput attribute.
    multiOutputInfos: A MultiOutputInfo attribute.
    numOutputs: A integer attribute.
    sideInputs: A SideInputInfo attribute.
    userFn: A UserFnValue attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class UserFnValue(messages.Message):
    """A UserFnValue object.

    Messages:
      AdditionalProperty: An additional property for a UserFnValue object.

    Fields:
      additionalProperties: Additional properties of type UserFnValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a UserFnValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  input = messages.MessageField('InstructionInput', 1)
  multiOutputInfos = messages.MessageField('MultiOutputInfo', 2, repeated=True)
  numOutputs = messages.IntegerField(3, variant=messages.Variant.INT32)
  sideInputs = messages.MessageField('SideInputInfo', 4, repeated=True)
  userFn = messages.MessageField('UserFnValue', 5)


class ParallelInstruction(messages.Message):
  """A ParallelInstruction object.

  Fields:
    flatten: A FlattenInstruction attribute.
    name: A string attribute.
    outputs: A InstructionOutput attribute.
    parDo: A ParDoInstruction attribute.
    partialGroupByKey: A PartialGroupByKeyInstruction attribute.
    read: A ReadInstruction attribute.
    systemName: A string attribute.
    write: A WriteInstruction attribute.
  """

  flatten = messages.MessageField('FlattenInstruction', 1)
  name = messages.StringField(2)
  outputs = messages.MessageField('InstructionOutput', 3, repeated=True)
  parDo = messages.MessageField('ParDoInstruction', 4)
  partialGroupByKey = messages.MessageField('PartialGroupByKeyInstruction', 5)
  read = messages.MessageField('ReadInstruction', 6)
  systemName = messages.StringField(7)
  write = messages.MessageField('WriteInstruction', 8)


class PartialGroupByKeyInstruction(messages.Message):
  """A PartialGroupByKeyInstruction object.

  Messages:
    InputElementCodecValue: A InputElementCodecValue object.
    ValueCombiningFnValue: A ValueCombiningFnValue object.

  Fields:
    input: A InstructionInput attribute.
    inputElementCodec: A InputElementCodecValue attribute.
    valueCombiningFn: A ValueCombiningFnValue attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class InputElementCodecValue(messages.Message):
    """A InputElementCodecValue object.

    Messages:
      AdditionalProperty: An additional property for a InputElementCodecValue
        object.

    Fields:
      additionalProperties: Additional properties of type
        InputElementCodecValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a InputElementCodecValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class ValueCombiningFnValue(messages.Message):
    """A ValueCombiningFnValue object.

    Messages:
      AdditionalProperty: An additional property for a ValueCombiningFnValue
        object.

    Fields:
      additionalProperties: Additional properties of type
        ValueCombiningFnValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a ValueCombiningFnValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  input = messages.MessageField('InstructionInput', 1)
  inputElementCodec = messages.MessageField('InputElementCodecValue', 2)
  valueCombiningFn = messages.MessageField('ValueCombiningFnValue', 3)


class Position(messages.Message):
  """A Position object.

  Fields:
    byteOffset: A string attribute.
    end: A boolean attribute.
    key: A string attribute.
    recordIndex: A string attribute.
    shufflePosition: A string attribute.
  """

  byteOffset = messages.IntegerField(1)
  end = messages.BooleanField(2)
  key = messages.StringField(3)
  recordIndex = messages.IntegerField(4)
  shufflePosition = messages.StringField(5)


class PubsubLocation(messages.Message):
  """A PubsubLocation object.

  Fields:
    dropLateData: A boolean attribute.
    idLabel: A string attribute.
    subscription: A string attribute.
    timestampLabel: A string attribute.
    topic: A string attribute.
    trackingSubscription: A string attribute.
  """

  dropLateData = messages.BooleanField(1)
  idLabel = messages.StringField(2)
  subscription = messages.StringField(3)
  timestampLabel = messages.StringField(4)
  topic = messages.StringField(5)
  trackingSubscription = messages.StringField(6)


class ReadInstruction(messages.Message):
  """A ReadInstruction object.

  Fields:
    source: A Source attribute.
  """

  source = messages.MessageField('Source', 1)


class ReportWorkItemStatusRequest(messages.Message):
  """A ReportWorkItemStatusRequest object.

  Fields:
    currentWorkerTime: A string attribute.
    workItemStatuses: A WorkItemStatus attribute.
    workerId: A string attribute.
  """

  currentWorkerTime = messages.StringField(1)
  workItemStatuses = messages.MessageField('WorkItemStatus', 2, repeated=True)
  workerId = messages.StringField(3)


class ReportWorkItemStatusResponse(messages.Message):
  """A ReportWorkItemStatusResponse object.

  Fields:
    workItemServiceStates: A WorkItemServiceState attribute.
  """

  workItemServiceStates = messages.MessageField('WorkItemServiceState', 1, repeated=True)


class SeqMapTask(messages.Message):
  """A SeqMapTask object.

  Messages:
    UserFnValue: A UserFnValue object.

  Fields:
    inputs: A SideInputInfo attribute.
    name: A string attribute.
    outputInfos: A SeqMapTaskOutputInfo attribute.
    stageName: A string attribute.
    systemName: A string attribute.
    userFn: A UserFnValue attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class UserFnValue(messages.Message):
    """A UserFnValue object.

    Messages:
      AdditionalProperty: An additional property for a UserFnValue object.

    Fields:
      additionalProperties: Additional properties of type UserFnValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a UserFnValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  inputs = messages.MessageField('SideInputInfo', 1, repeated=True)
  name = messages.StringField(2)
  outputInfos = messages.MessageField('SeqMapTaskOutputInfo', 3, repeated=True)
  stageName = messages.StringField(4)
  systemName = messages.StringField(5)
  userFn = messages.MessageField('UserFnValue', 6)


class SeqMapTaskOutputInfo(messages.Message):
  """A SeqMapTaskOutputInfo object.

  Fields:
    sink: A Sink attribute.
    tag: A string attribute.
  """

  sink = messages.MessageField('Sink', 1)
  tag = messages.StringField(2)


class ShellTask(messages.Message):
  """A ShellTask object.

  Fields:
    command: A string attribute.
    exitCode: A integer attribute.
  """

  command = messages.StringField(1)
  exitCode = messages.IntegerField(2, variant=messages.Variant.INT32)


class SideInputInfo(messages.Message):
  """A SideInputInfo object.

  Messages:
    KindValue: A KindValue object.

  Fields:
    kind: A KindValue attribute.
    sources: A Source attribute.
    tag: A string attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class KindValue(messages.Message):
    """A KindValue object.

    Messages:
      AdditionalProperty: An additional property for a KindValue object.

    Fields:
      additionalProperties: Additional properties of type KindValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a KindValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  kind = messages.MessageField('KindValue', 1)
  sources = messages.MessageField('Source', 2, repeated=True)
  tag = messages.StringField(3)


class Sink(messages.Message):
  """A Sink object.

  Messages:
    CodecValue: A CodecValue object.
    SpecValue: A SpecValue object.

  Fields:
    codec: A CodecValue attribute.
    spec: A SpecValue attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class CodecValue(messages.Message):
    """A CodecValue object.

    Messages:
      AdditionalProperty: An additional property for a CodecValue object.

    Fields:
      additionalProperties: Additional properties of type CodecValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a CodecValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class SpecValue(messages.Message):
    """A SpecValue object.

    Messages:
      AdditionalProperty: An additional property for a SpecValue object.

    Fields:
      additionalProperties: Additional properties of type SpecValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a SpecValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  codec = messages.MessageField('CodecValue', 1)
  spec = messages.MessageField('SpecValue', 2)


class Source(messages.Message):
  """A Source object.

  Messages:
    BaseSpecsValueListEntry: A BaseSpecsValueListEntry object.
    CodecValue: A CodecValue object.
    SpecValue: A SpecValue object.

  Fields:
    baseSpecs: A BaseSpecsValueListEntry attribute.
    codec: A CodecValue attribute.
    doesNotNeedSplitting: A boolean attribute.
    metadata: A SourceMetadata attribute.
    spec: A SpecValue attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class BaseSpecsValueListEntry(messages.Message):
    """A BaseSpecsValueListEntry object.

    Messages:
      AdditionalProperty: An additional property for a BaseSpecsValueListEntry
        object.

    Fields:
      additionalProperties: Additional properties of type
        BaseSpecsValueListEntry
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a BaseSpecsValueListEntry object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class CodecValue(messages.Message):
    """A CodecValue object.

    Messages:
      AdditionalProperty: An additional property for a CodecValue object.

    Fields:
      additionalProperties: Additional properties of type CodecValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a CodecValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class SpecValue(messages.Message):
    """A SpecValue object.

    Messages:
      AdditionalProperty: An additional property for a SpecValue object.

    Fields:
      additionalProperties: Additional properties of type SpecValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a SpecValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  baseSpecs = messages.MessageField('BaseSpecsValueListEntry', 1, repeated=True)
  codec = messages.MessageField('CodecValue', 2)
  doesNotNeedSplitting = messages.BooleanField(3)
  metadata = messages.MessageField('SourceMetadata', 4)
  spec = messages.MessageField('SpecValue', 5)


class SourceFork(messages.Message):
  """A SourceFork object.

  Fields:
    primary: A SourceSplitShard attribute.
    residual: A SourceSplitShard attribute.
  """

  primary = messages.MessageField('SourceSplitShard', 1)
  residual = messages.MessageField('SourceSplitShard', 2)


class SourceGetMetadataRequest(messages.Message):
  """A SourceGetMetadataRequest object.

  Fields:
    source: A Source attribute.
  """

  source = messages.MessageField('Source', 1)


class SourceGetMetadataResponse(messages.Message):
  """A SourceGetMetadataResponse object.

  Fields:
    metadata: A SourceMetadata attribute.
  """

  metadata = messages.MessageField('SourceMetadata', 1)


class SourceMetadata(messages.Message):
  """A SourceMetadata object.

  Fields:
    estimatedSizeBytes: A string attribute.
    infinite: A boolean attribute.
    producesSortedKeys: A boolean attribute.
  """

  estimatedSizeBytes = messages.IntegerField(1)
  infinite = messages.BooleanField(2)
  producesSortedKeys = messages.BooleanField(3)


class SourceOperationRequest(messages.Message):
  """A SourceOperationRequest object.

  Fields:
    getMetadata: A SourceGetMetadataRequest attribute.
    split: A SourceSplitRequest attribute.
  """

  getMetadata = messages.MessageField('SourceGetMetadataRequest', 1)
  split = messages.MessageField('SourceSplitRequest', 2)


class SourceOperationResponse(messages.Message):
  """A SourceOperationResponse object.

  Fields:
    getMetadata: A SourceGetMetadataResponse attribute.
    split: A SourceSplitResponse attribute.
  """

  getMetadata = messages.MessageField('SourceGetMetadataResponse', 1)
  split = messages.MessageField('SourceSplitResponse', 2)


class SourceSplitOptions(messages.Message):
  """A SourceSplitOptions object.

  Fields:
    desiredShardSizeBytes: A string attribute.
  """

  desiredShardSizeBytes = messages.IntegerField(1)


class SourceSplitRequest(messages.Message):
  """A SourceSplitRequest object.

  Fields:
    options: A SourceSplitOptions attribute.
    source: A Source attribute.
  """

  options = messages.MessageField('SourceSplitOptions', 1)
  source = messages.MessageField('Source', 2)


class SourceSplitResponse(messages.Message):
  """A SourceSplitResponse object.

  Enums:
    OutcomeValueValuesEnum:

  Fields:
    outcome: A OutcomeValueValuesEnum attribute.
    shards: A SourceSplitShard attribute.
  """

  class OutcomeValueValuesEnum(messages.Enum):
    """OutcomeValueValuesEnum enum type.

    Values:
      SOURCE_SPLIT_OUTCOME_SPLITTING_HAPPENED: <no description>
      SOURCE_SPLIT_OUTCOME_UNKNOWN: <no description>
      SOURCE_SPLIT_OUTCOME_USE_CURRENT: <no description>
    """
    SOURCE_SPLIT_OUTCOME_SPLITTING_HAPPENED = 0
    SOURCE_SPLIT_OUTCOME_UNKNOWN = 1
    SOURCE_SPLIT_OUTCOME_USE_CURRENT = 2

  outcome = messages.EnumField('OutcomeValueValuesEnum', 1)
  shards = messages.MessageField('SourceSplitShard', 2, repeated=True)


class SourceSplitShard(messages.Message):
  """A SourceSplitShard object.

  Enums:
    DerivationModeValueValuesEnum:

  Fields:
    derivationMode: A DerivationModeValueValuesEnum attribute.
    source: A Source attribute.
  """

  class DerivationModeValueValuesEnum(messages.Enum):
    """DerivationModeValueValuesEnum enum type.

    Values:
      SOURCE_DERIVATION_MODE_CHILD_OF_CURRENT: <no description>
      SOURCE_DERIVATION_MODE_INDEPENDENT: <no description>
      SOURCE_DERIVATION_MODE_SIBLING_OF_CURRENT: <no description>
      SOURCE_DERIVATION_MODE_UNKNOWN: <no description>
    """
    SOURCE_DERIVATION_MODE_CHILD_OF_CURRENT = 0
    SOURCE_DERIVATION_MODE_INDEPENDENT = 1
    SOURCE_DERIVATION_MODE_SIBLING_OF_CURRENT = 2
    SOURCE_DERIVATION_MODE_UNKNOWN = 3

  derivationMode = messages.EnumField('DerivationModeValueValuesEnum', 1)
  source = messages.MessageField('Source', 2)


class StandardQueryParameters(messages.Message):
  """Query parameters accepted by all methods.

  Enums:
    AltValueValuesEnum: Data format for the response.

  Fields:
    alt: Data format for the response.
    fields: Selector specifying which fields to include in a partial response.
    key: API key. Your API key identifies your project and provides you with
      API access, quota, and reports. Required unless you provide an OAuth 2.0
      token.
    oauth_token: OAuth 2.0 token for the current user.
    prettyPrint: Returns response with indentations and line breaks.
    quotaUser: Available to use for quota purposes for server-side
      applications. Can be any arbitrary string assigned to a user, but should
      not exceed 40 characters. Overrides userIp if both are provided.
    trace: A tracing token of the form "token:<tokenid>" or "email:<ldap>" to
      include in api requests.
    userIp: IP address of the site where the request originates. Use this if
      you want to enforce per-user limits.
  """

  class AltValueValuesEnum(messages.Enum):
    """Data format for the response.

    Values:
      json: Responses with Content-Type of application/json
    """
    json = 0

  alt = messages.EnumField('AltValueValuesEnum', 1, default=u'json')
  fields = messages.StringField(2)
  key = messages.StringField(3)
  oauth_token = messages.StringField(4)
  prettyPrint = messages.BooleanField(5, default=True)
  quotaUser = messages.StringField(6)
  trace = messages.StringField(7)
  userIp = messages.StringField(8)


class Status(messages.Message):
  """A Status object.

  Messages:
    DetailsValueListEntry: A DetailsValueListEntry object.

  Fields:
    code: A integer attribute.
    details: A DetailsValueListEntry attribute.
    message: A string attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class DetailsValueListEntry(messages.Message):
    """A DetailsValueListEntry object.

    Messages:
      AdditionalProperty: An additional property for a DetailsValueListEntry
        object.

    Fields:
      additionalProperties: Additional properties of type
        DetailsValueListEntry
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a DetailsValueListEntry object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  code = messages.IntegerField(1, variant=messages.Variant.INT32)
  details = messages.MessageField('DetailsValueListEntry', 2, repeated=True)
  message = messages.StringField(3)


class Step(messages.Message):
  """A Step object.

  Messages:
    PropertiesValue: A PropertiesValue object.

  Fields:
    kind: A string attribute.
    name: A string attribute.
    properties: A PropertiesValue attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class PropertiesValue(messages.Message):
    """A PropertiesValue object.

    Messages:
      AdditionalProperty: An additional property for a PropertiesValue object.

    Fields:
      additionalProperties: Additional properties of type PropertiesValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a PropertiesValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  kind = messages.StringField(1)
  name = messages.StringField(2)
  properties = messages.MessageField('PropertiesValue', 3)


class StreamLocation(messages.Message):
  """A StreamLocation object.

  Fields:
    pubsubLocation: A PubsubLocation attribute.
    streamingStageLocation: A StreamingStageLocation attribute.
  """

  pubsubLocation = messages.MessageField('PubsubLocation', 1)
  streamingStageLocation = messages.MessageField('StreamingStageLocation', 2)


class StreamingComputationRanges(messages.Message):
  """A StreamingComputationRanges object.

  Fields:
    computationId: A string attribute.
    rangeAssignments: A KeyRangeDataDiskAssignment attribute.
  """

  computationId = messages.StringField(1)
  rangeAssignments = messages.MessageField('KeyRangeDataDiskAssignment', 2, repeated=True)


class StreamingComputationTask(messages.Message):
  """A StreamingComputationTask object.

  Enums:
    TaskTypeValueValuesEnum:

  Fields:
    computationRanges: A StreamingComputationRanges attribute.
    dataDisks: A MountedDataDisk attribute.
    taskType: A TaskTypeValueValuesEnum attribute.
  """

  class TaskTypeValueValuesEnum(messages.Enum):
    """TaskTypeValueValuesEnum enum type.

    Values:
      STREAMING_COMPUTATION_TASK_START: <no description>
      STREAMING_COMPUTATION_TASK_STOP: <no description>
      STREAMING_COMPUTATION_TASK_UNKNOWN: <no description>
    """
    STREAMING_COMPUTATION_TASK_START = 0
    STREAMING_COMPUTATION_TASK_STOP = 1
    STREAMING_COMPUTATION_TASK_UNKNOWN = 2

  computationRanges = messages.MessageField('StreamingComputationRanges', 1, repeated=True)
  dataDisks = messages.MessageField('MountedDataDisk', 2, repeated=True)
  taskType = messages.EnumField('TaskTypeValueValuesEnum', 3)


class StreamingSetupTask(messages.Message):
  """A StreamingSetupTask object.

  Fields:
    receiveWorkPort: A integer attribute.
    streamingComputationTopology: A TopologyConfig attribute.
    workerHarnessPort: A integer attribute.
  """

  receiveWorkPort = messages.IntegerField(1, variant=messages.Variant.INT32)
  streamingComputationTopology = messages.MessageField('TopologyConfig', 2)
  workerHarnessPort = messages.IntegerField(3, variant=messages.Variant.INT32)


class StreamingStageLocation(messages.Message):
  """A StreamingStageLocation object.

  Fields:
    streamId: A string attribute.
  """

  streamId = messages.StringField(1)


class TaskRunnerSettings(messages.Message):
  """A TaskRunnerSettings object.

  Fields:
    alsologtostderr: A boolean attribute.
    baseTaskDir: A string attribute.
    baseUrl: A string attribute.
    commandlinesFileName: A string attribute.
    continueOnException: A boolean attribute.
    dataflowApiVersion: A string attribute.
    harnessCommand: A string attribute.
    languageHint: A string attribute.
    logDir: A string attribute.
    logToSerialconsole: A boolean attribute.
    logUploadLocation: A string attribute.
    oauthScopes: A string attribute.
    parallelWorkerSettings: A WorkerSettings attribute.
    streamingWorkerMainClass: A string attribute.
    taskGroup: A string attribute.
    taskUser: A string attribute.
    tempStoragePrefix: A string attribute.
    vmId: A string attribute.
    workflowFileName: A string attribute.
  """

  alsologtostderr = messages.BooleanField(1)
  baseTaskDir = messages.StringField(2)
  baseUrl = messages.StringField(3)
  commandlinesFileName = messages.StringField(4)
  continueOnException = messages.BooleanField(5)
  dataflowApiVersion = messages.StringField(6)
  harnessCommand = messages.StringField(7)
  languageHint = messages.StringField(8)
  logDir = messages.StringField(9)
  logToSerialconsole = messages.BooleanField(10)
  logUploadLocation = messages.StringField(11)
  oauthScopes = messages.StringField(12, repeated=True)
  parallelWorkerSettings = messages.MessageField('WorkerSettings', 13)
  streamingWorkerMainClass = messages.StringField(14)
  taskGroup = messages.StringField(15)
  taskUser = messages.StringField(16)
  tempStoragePrefix = messages.StringField(17)
  vmId = messages.StringField(18)
  workflowFileName = messages.StringField(19)


class TopologyConfig(messages.Message):
  """A TopologyConfig object.

  Fields:
    computations: A ComputationTopology attribute.
    dataDiskAssignments: A DataDiskAssignment attribute.
  """

  computations = messages.MessageField('ComputationTopology', 1, repeated=True)
  dataDiskAssignments = messages.MessageField('DataDiskAssignment', 2, repeated=True)


class WorkItem(messages.Message):
  """A WorkItem object.

  Fields:
    configuration: A string attribute.
    id: A string attribute.
    initialReportIndex: A string attribute.
    jobId: A string attribute.
    leaseExpireTime: A string attribute.
    mapTask: A MapTask attribute.
    packages: A Package attribute.
    projectId: A string attribute.
    reportStatusInterval: A string attribute.
    seqMapTask: A SeqMapTask attribute.
    shellTask: A ShellTask attribute.
    sourceOperationTask: A SourceOperationRequest attribute.
    streamingComputationTask: A StreamingComputationTask attribute.
    streamingSetupTask: A StreamingSetupTask attribute.
  """

  configuration = messages.StringField(1)
  id = messages.IntegerField(2)
  initialReportIndex = messages.IntegerField(3)
  jobId = messages.StringField(4)
  leaseExpireTime = messages.StringField(5)
  mapTask = messages.MessageField('MapTask', 6)
  packages = messages.MessageField('Package', 7, repeated=True)
  projectId = messages.StringField(8)
  reportStatusInterval = messages.StringField(9)
  seqMapTask = messages.MessageField('SeqMapTask', 10)
  shellTask = messages.MessageField('ShellTask', 11)
  sourceOperationTask = messages.MessageField('SourceOperationRequest', 12)
  streamingComputationTask = messages.MessageField('StreamingComputationTask', 13)
  streamingSetupTask = messages.MessageField('StreamingSetupTask', 14)


class WorkItemServiceState(messages.Message):
  """A WorkItemServiceState object.

  Messages:
    HarnessDataValue: A HarnessDataValue object.

  Fields:
    harnessData: A HarnessDataValue attribute.
    leaseExpireTime: A string attribute.
    nextReportIndex: A string attribute.
    reportStatusInterval: A string attribute.
    suggestedStopPoint: A ApproximateProgress attribute.
    suggestedStopPosition: A Position attribute.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class HarnessDataValue(messages.Message):
    """A HarnessDataValue object.

    Messages:
      AdditionalProperty: An additional property for a HarnessDataValue
        object.

    Fields:
      additionalProperties: Additional properties of type HarnessDataValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a HarnessDataValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = messages.StringField(1)
      value = messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  harnessData = messages.MessageField('HarnessDataValue', 1)
  leaseExpireTime = messages.StringField(2)
  nextReportIndex = messages.IntegerField(3)
  reportStatusInterval = messages.StringField(4)
  suggestedStopPoint = messages.MessageField('ApproximateProgress', 5)
  suggestedStopPosition = messages.MessageField('Position', 6)


class WorkItemStatus(messages.Message):
  """A WorkItemStatus object.

  Fields:
    completed: A boolean attribute.
    errors: A Status attribute.
    metricUpdates: A MetricUpdate attribute.
    progress: A ApproximateProgress attribute.
    reportIndex: A string attribute.
    requestedLeaseDuration: A string attribute.
    sourceFork: A SourceFork attribute.
    sourceOperationResponse: A SourceOperationResponse attribute.
    stopPosition: A Position attribute.
    workItemId: A string attribute.
  """

  completed = messages.BooleanField(1)
  errors = messages.MessageField('Status', 2, repeated=True)
  metricUpdates = messages.MessageField('MetricUpdate', 3, repeated=True)
  progress = messages.MessageField('ApproximateProgress', 4)
  reportIndex = messages.IntegerField(5)
  requestedLeaseDuration = messages.StringField(6)
  sourceFork = messages.MessageField('SourceFork', 7)
  sourceOperationResponse = messages.MessageField('SourceOperationResponse', 8)
  stopPosition = messages.MessageField('Position', 9)
  workItemId = messages.StringField(10)


class WorkerPool(messages.Message):
  """A WorkerPool object.

  Enums:
    DefaultPackageSetValueValuesEnum:
    TeardownPolicyValueValuesEnum:

  Messages:
    MetadataValue: A MetadataValue object.

  Fields:
    autoscalingSettings: A AutoscalingSettings attribute.
    dataDisks: A Disk attribute.
    defaultPackageSet: A DefaultPackageSetValueValuesEnum attribute.
    diskSizeGb: A integer attribute.
    diskSourceImage: A string attribute.
    kind: A string attribute.
    machineType: A string attribute.
    metadata: A MetadataValue attribute.
    numWorkers: A integer attribute.
    onHostMaintenance: A string attribute.
    packages: A Package attribute.
    taskrunnerSettings: A TaskRunnerSettings attribute.
    teardownPolicy: A TeardownPolicyValueValuesEnum attribute.
    zone: A string attribute.
  """

  class DefaultPackageSetValueValuesEnum(messages.Enum):
    """DefaultPackageSetValueValuesEnum enum type.

    Values:
      DEFAULT_PACKAGE_SET_JAVA: <no description>
      DEFAULT_PACKAGE_SET_NONE: <no description>
      DEFAULT_PACKAGE_SET_PYTHON: <no description>
      DEFAULT_PACKAGE_SET_UNKNOWN: <no description>
    """
    DEFAULT_PACKAGE_SET_JAVA = 0
    DEFAULT_PACKAGE_SET_NONE = 1
    DEFAULT_PACKAGE_SET_PYTHON = 2
    DEFAULT_PACKAGE_SET_UNKNOWN = 3

  class TeardownPolicyValueValuesEnum(messages.Enum):
    """TeardownPolicyValueValuesEnum enum type.

    Values:
      TEARDOWN_ALWAYS: <no description>
      TEARDOWN_NEVER: <no description>
      TEARDOWN_ON_SUCCESS: <no description>
      TEARDOWN_POLICY_UNKNOWN: <no description>
    """
    TEARDOWN_ALWAYS = 0
    TEARDOWN_NEVER = 1
    TEARDOWN_ON_SUCCESS = 2
    TEARDOWN_POLICY_UNKNOWN = 3

  @encoding.MapUnrecognizedFields('additionalProperties')
  class MetadataValue(messages.Message):
    """A MetadataValue object.

    Messages:
      AdditionalProperty: An additional property for a MetadataValue object.

    Fields:
      additionalProperties: Additional properties of type MetadataValue
    """

    class AdditionalProperty(messages.Message):
      """An additional property for a MetadataValue object.

      Fields:
        key: Name of the additional property.
        value: A string attribute.
      """

      key = messages.StringField(1)
      value = messages.StringField(2)

    additionalProperties = messages.MessageField('AdditionalProperty', 1, repeated=True)

  autoscalingSettings = messages.MessageField('AutoscalingSettings', 1)
  dataDisks = messages.MessageField('Disk', 2, repeated=True)
  defaultPackageSet = messages.EnumField('DefaultPackageSetValueValuesEnum', 3)
  diskSizeGb = messages.IntegerField(4, variant=messages.Variant.INT32)
  diskSourceImage = messages.StringField(5)
  kind = messages.StringField(6)
  machineType = messages.StringField(7)
  metadata = messages.MessageField('MetadataValue', 8)
  numWorkers = messages.IntegerField(9, variant=messages.Variant.INT32)
  onHostMaintenance = messages.StringField(10)
  packages = messages.MessageField('Package', 11, repeated=True)
  taskrunnerSettings = messages.MessageField('TaskRunnerSettings', 12)
  teardownPolicy = messages.EnumField('TeardownPolicyValueValuesEnum', 13)
  zone = messages.StringField(14)


class WorkerSettings(messages.Message):
  """A WorkerSettings object.

  Fields:
    baseUrl: A string attribute.
    reportingEnabled: A boolean attribute.
    servicePath: A string attribute.
    shuffleServicePath: A string attribute.
    tempStoragePrefix: A string attribute.
    workerId: A string attribute.
  """

  baseUrl = messages.StringField(1)
  reportingEnabled = messages.BooleanField(2)
  servicePath = messages.StringField(3)
  shuffleServicePath = messages.StringField(4)
  tempStoragePrefix = messages.StringField(5)
  workerId = messages.StringField(6)


class WriteInstruction(messages.Message):
  """A WriteInstruction object.

  Fields:
    input: A InstructionInput attribute.
    sink: A Sink attribute.
  """

  input = messages.MessageField('InstructionInput', 1)
  sink = messages.MessageField('Sink', 2)


