application: movie-miner
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /.*
  script: main.application

libraries:
- name: ssl
  version: latest

builtins:
- remote_api: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'MovieMiner.settings'